site_name: Hướng dẫn sử dụng hệ thống vESS

nav:
    - 'Trang chủ': 'index.md'
    - 'Đăng ký, đăng nhập': 
        - 'Đăng ký & cài đặt': 'saas/saas.md'
        - 'Đăng nhập, đăng xuất': 'digitalworkplace/Addon-login.md'
        - 'Đăng nhập bằng QR code': 'digitalworkplace/Addon-QRcode.md'
        - 'Đăng nhập bằng G+': 'digitalworkplace/Addon-DangNhapG.md'
        - 'Xác thực 2 bước': 'digitalworkplace/Addon-xac-thuc-hai-buoc.md'
    - 'Nhân sự': 
        - 'Giới thiệu về phân hệ Quản lý nhân sự': 'hrm/introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'hrm/initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'hrm/abbreviations.md'
        - 'Khai báo danh mục': 'hrm/master-datas.md'
        - 'Tuyển dụng': 'hrm/recruitment.md'
        - 'Nhân viên': 'hrm/employee.md'
        - 'Chấm công': 'hrm/attendance.md'
        - 'Tính lương': 'hrm/payroll.md'
        - 'Lịch sử phát triển sản phẩm': 'hrm/log-histories.md'
    - 'Kế toán': 
        - 'Giới thiệu về phân hệ Kế toán': 'finance/fin-introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'finance/fin-initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'finance/fin-abbreviations.md'
        - 'Khai báo danh mục': 'finance/fin-danh-muc-new.md'
        - 'Quản lý tiền - Tiền mặt': 'finance/fin-tien-TM.md'
        - 'Quản lý tiền - Tiền gửi': 'finance/fin-tien-NH.md'
        - 'Mua hàng': 'finance/fin-mua-hang.md'
        - 'Bán hàng': 'finance/fin-ban-hang.md'
        - 'Kế toán': 'finance/fin-ke-toan-tong-hop.md'
        - 'Kho vận': 'finance/fin-kho.md'
            # - 'Sản xuất': 'finance/fin-san-xuat.md'
        - 'Tài sản cố định': 'finance/fin-tscd.md'
        - 'Công cụ dụng cụ': 'finance/fin-ccdc.md'
        - 'Lịch sử phát triển sản phẩm': 'finance/fin-log-histories.md'
    - 'Tài liệu': 
        - 'Giới thiệu về ứng dụng Tài liệu': 'document/introduction.md'
        - 'Các thuật ngữ và từ viết tắt': 'document/abbreviations.md'
        - 'Thiết lập và khai báo ban đầu': 'document/initialization.md'
        - 'Tài liệu': 'document/document.md'   
    - 'Ký số': 
        - 'Giới thiệu về ứng dụng Ký số': 'esign/introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'esign/initialization.md'
        - 'Ký số': 'esign/esign.md'           
    - 'Digital workplace': 
        - 'Giới thiệu về phân hệ Digital workplace': 'digitalworkplace/Gioi-thieu-digital-workplace.md'
        - 'Thiết lập và khai báo ban đầu': 'digitalworkplace/dw-initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'digitalworkplace/Thuat-ngu-viet-tat.md'
        - 'Trang web': 'digitalworkplace/Addon-Website.md'
        - 'Mạng xã hội': 'digitalworkplace/Addon-Social.md'
        - 'Dự án': 'digitalworkplace/Addon-project.md'
        - 'Khảo sát': 'digitalworkplace/Addon-khao-sat.md'
        - 'Ghi chú': 'digitalworkplace/Addon-ghi-chu.md'
        - 'Timesheet': 'digitalworkplace/Addon-timesheet.md'
        - 'Sự kiện': 'digitalworkplace/Addon-su-kien.md'
        - 'Bữa ăn': 'digitalworkplace/Addon-bua-an.md'
        - 'Lịch sử phát triển sản phẩm': 'digitalworkplace/Lich-su-phat-trien.md'
        - 'Phê duyệt trên web': 'digitalworkplace/Addon-PheDuyet-Web.md'
    - 'vESS Mobile': 
        - 'Giới thiệu về vESS mobile': 'vESS_mobile/Gioi-thieu-vess-mobile.md'
        - 'Thiết lập và khai báo ban đầu': 'vESS_mobile/Mobile-initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'vESS_mobile/Thuat-ngu-viet-tat.md'
        - 'Đăng nhập': 'vESS_mobile/Mobile-dang-nhap.md'
        - 'Phê duyệt trên mobile': 'vESS_mobile/Addon-phe-duyet.md'
        - 'Lịch sử phát triển sản phẩm': 'vESS_mobile/Mobile-Lich-su-phat-trien.md'
    - 'Release Notes': 'release-notes.md'
theme:
    name: readthedocs
    navigation_depth: 100
    highlightjs: true
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js